EXAMPLESDIR=../../platform/avr-rss2/examples
TOOLSDIR=../../tools

# build jn516x examples, covering IPv6, RPL, CoAP, Rime, Nullrdc, Contikimac

EXAMPLES = \
hello-sensors/avr-rss2 \
ipv6/rpl-udp-report/avr-rss2 
TOOLS=

include ../Makefile.compile-test
